[manager]
show_hidden = true
show_symlink = true
[opener]
edit = [ {run = 'nvim "$@"', block = true, for = "unix"  }]
play = [ { run = 'vlc "$@"', desc = "VLC", orphan = true }]
[plugin]
prepend_previewers = [
    { name = "*.md", run  = 'glow'},
]
